version: '2'
services:
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - '~/.lapdance/settings:/app/settings'
      - '~/.lapdance/db:/app/.db'
      - '~/.lapdance/logs:/app/logs'
      - '~/.lapdance/scripts:/scripts'
    ports:
      - '5000:80'
