version: '2'
services:
  redap:
    image: rbw0/redap:latest
    volumes:
      - '~/.redap/settings:/app/settings'
      - '~/.redap/db:/app/.db'
      - '~/.redap/logs:/app/logs'
      - '~/.redap/scripts:/scripts'
    ports:
      - '5000:80'
