version: '2'
services:
  redap:
    image: rbw0/redap:latest
    volumes:
      - '~/.redap/settings:/app/settings'
      - '~/.redap/db:/app/.db'
      - '~/.redap/logs:/app/logs'
      - '~/.redap/scripts:/scripts'
      - '~/.redap/certs:/certs'
    ports:
      - '5000:80'
    environment:
      - USE_SSL=0  # Looks for cert.crt and cert.key in ~/.redap/certs, if enabled.
      - WORKER_PROCESSES=4
